### ISSUE TITLE
Wrong executable format on flomp/wanderer-db image

### ISSUE THREAD

**Issue by callum-99** [Flomp/wanderer#1]
Just a small issue with your docker image for the database. Currently the executable is built for arm64: 
```shell
pocketbase: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=Ypg7785avPSIhmw-I2_z/cEYv5F-E4-7xfmVePnOh/sPjUGfxd6wd_odGwtFZ-/ir6okl09Mx4CbzeSaRP0, with debug_info, not stripped
```
so produces the following output when ran:
```shell
wanderer-db  | exec /pocketbase: exec format error
```

I am currently deploying on an amd64 machine.

Excited to check this out when the image is fixed. Thanks

**Comment by Flomp** [comment]
Thank you for the hint! What a silly oversight on my part...
I fixed the wanderer-db docker image. Tested it on an x86_64 machine. 
Could you please confirm?

**Comment by callum-99** [comment]
Yep thats all fixed now. Thanks for the quick fix!
