### ISSUE TITLE
Add route with attached file not showing and no error

### ISSUE THREAD

**Issue by garbast** [Flomp/wanderer#10]
When i try to upload the attached gpx file with name "Düsseldorf-Angermund nach Neuss-Hamm" the ui shows a "Trail saved successful" but no route is found in the list and NO error is present in the docker log view.

[2021-11-14_564807964_Düsseldorf-Angermund nach Neuss-Hamm.gpx.txt](https://github.com/Flomp/wanderer/files/14627079/2021-11-14_564807964_Dusseldorf-Angermund.nach.Neuss-Hamm.gpx.txt)

**Comment by Flomp** [comment]
Thanks for posting the file. That was very helpful in debugging. In a sense wanderer behaves correctly. The "problem" is that the track is longer than 24km. But the distance filter goes only up to 20km.
I now adapted the filter to show everything when it is set to the maximum setting. This will be included in the upcoming patch.

**Comment by Flomp** [comment]
I just released v0.1.1. The issue should be resolved now.
