### ISSUE TITLE
Hosted it failed when use docker

### ISSUE THREAD

**Issue by ultwcz** [Flomp/wanderer#100]
Hi, Flomp:
Following the [guide](https://wanderer.to/getting-started/installation/#docker),
the command `docker compose up -d` failed, and I used `docker-compose up -d` instead of it;
but it show error:
> ERROR: The Compose file './docker-compose.yml' is invalid because:
services.search.environment.MEILI_NO_ANALYTICS contains true, which is an invalid type, it should be a string, number, or a null
services.web.environment.PUBLIC_DISABLE_SIGNUP contains false, which is an invalid type, it should be a string, number, or a null

What should I do next? 
Thanks.

BTW,
system OS: Linux debian 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux
docker-compose --version: docker-compose version 1.29.2, build unknown

**Comment by Flomp** [comment]
Your docker compose is [3 years old](https://docs.docker.com/compose/release-notes/#1292) and likely does not support all APIs used in wanderer's docker-compose.yml. Please update your docker installation and see if see error persists.

**Comment by ultwcz** [comment]
Ok, thank you.
Now I replace true to "true", it can work normally.
```
diff --git a/docker-compose.yml b/docker-compose.yml
index f5680eb..b46f712 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -10,13 +10,13 @@ services:
     image: flomp/wanderer-search
     environment:
       <<: *cenv
-      MEILI_NO_ANALYTICS: true
+      MEILI_NO_ANALYTICS: "true"
@@ -49,18 +49,18 @@ services:
         condition: service_started
     environment:
       <<: *cenv
      ORIGIN: http://localhost:3000
       BODY_SIZE_LIMIT: Infinity
       PUBLIC_POCKETBASE_URL: http://db:8090
-      PUBLIC_DISABLE_SIGNUP: false
+      PUBLIC_DISABLE_SIGNUP: "false"
```
