### ISSUE TITLE
Trail details page changed map to be very short

### ISSUE THREAD

**Issue by domodwyer** [Flomp/wanderer#101]
Since v0.7.3 the trail details page has shown a much shorter map view, and the page footer bar has floated up from the bottom of the window:

![image](https://github.com/user-attachments/assets/f251e050-5dcf-4f8a-9052-42e5d9365f28)

You can see it on the [demo site too](https://demo.wanderer.to/map/trail/jmolew6qjtkmx5f).

However the "maps" page has full height:

![image](https://github.com/user-attachments/assets/222d38da-4cb7-47e7-9afe-353910d8b958)

The map on trail details page was full height in v0.7.2:

![image](https://github.com/user-attachments/assets/ceae67fe-167d-436d-8632-e747a5bb2e20)

It seems the map + elevation display have the same height as the trail details card on the left. 

I'm using Firefox, but I've also checked with Safari.

**Comment by Flomp** [comment]
Thanks for the hint. That is unintentional. I'll fix it with the next update.

**Comment by domodwyer** [comment]
That's great! Thanks for the dedication @Flomp 🚀

**Comment by Flomp** [comment]
Fixed in v0.8.2.
