### ISSUE TITLE
Suggestion: Page menu should appear at the bottom of the list

### ISSUE THREAD

**Issue by BastLast** [Flomp/wanderer#104]
![image](https://github.com/user-attachments/assets/6807ce14-4e33-4352-8960-cd8d41f48990)
![image](https://github.com/user-attachments/assets/561f8a3a-e89b-4c5d-9cf8-97d6fc79ad10)
the page thing should be displayed, user should not have to scroll up to change page

**Comment by Flomp** [comment]
Added in v0.8.2.
