### ISSUE TITLE
[Feature Request] Device geolocation

### ISSUE THREAD

**Issue by jarex691** [Flomp/wanderer#106]
It would be great to have the geolocation of my device visible on the active map and know where I am currently on the route or how far I am from it. Directions to the starting point would also be on such maps.

**Comment by bevalentin** [comment]
Hi,

Do you have in mind something similar to [μLogger](https://github.com/bfabiszewski/ulogger-server) ?
It even comes with a [mobile client for Android](https://github.com/bfabiszewski/ulogger-android).
And here is [what it looks like on the web](https://ulogger.lima.zone/#1/o/1670378.8099147875/4539543.024417232/14.736600681491831/0).

Note that I am in no way involved with μLogger.
But if it suits users needs, maybe a "bridge" would be sufficient, like being able to import tracks stored in μLogger using its API.

Just a suggestion.

**Comment by Flomp** [comment]
Hey,

While I agree that this would be awesome this would be a huge undertaking and is currently out of scope. There already are plenty of great (open-source) apps that do exactly what you ask (personally I really like osmAnd). Simply export your trails from wanderer as a GPX and import them into your favourite maps app.

**Comment by jarex691** [comment]
Hi I was thinking of simply retrieving location data from the browser like here  visitglacensis.pl https://visitglacensis.pl/old/  I cared more about the current position, directions is not important anymore.  
     
      
       
        Dnia 03 września 2024 17:24 Flomp ***@***.***&gt; napisał(a):
       
    
       
         
 Hey, 
 While I agree that this would be awesome this would be a huge undertaking and is currently out of scope. There already are plenty of great (open-source) apps that do exactly what you ask (personally I really like osmAnd). Simply export your trails from wanderer as a GPX and import them into your favourite maps app.
