### ISSUE TITLE
Main website down ?

### ISSUE THREAD

**Issue by Frankynov** [Flomp/wanderer#109]
Hello ! 
I just tried to access the documentation, and unfortunately it looks like the main wanderer.to website is down.
I'm getting : 

```
502 Bad Gateway
nginx/1.18.0 (Ubuntu)
```

Any maintenance going on ?
Thank you ! :)

**Comment by Flomp** [comment]
Hey,

Thanks for the hint. I'm aware, but currently on the road. Will be back by tomorrow night.

**Comment by Flomp** [comment]
Website is back. Sorry for the inconvenience.
