### ISSUE TITLE
[improvement] Possible to upload several GPX files at once?

### ISSUE THREAD

**Issue by asitemade4u** [Flomp/wanderer#11]
Hi,
Thank you for the very promising tool -- just what I was looking for!
I have hundreds of `gpx` files and was wondering if it would be possible to upload them all at once, then refine the records for each.
Doing it programmatically through the API would be fine with me.

Thx,
S.

**Comment by Flomp** [comment]
With the new release v0.2.0 you can now upload trails through the API. Please check the [documentation](https://github.com/Flomp/wanderer/wiki/API#upload-trails) for more info.
