### ISSUE TITLE
Pictures - Can't Upload HEIC

### ISSUE THREAD

**Issue by noja11** [Flomp/wanderer#110]
Hi There,

Thanks so much for this amazing software. I just want to confirm that I'm not crazy and that HEIC photos are not able to be uploaded. I tried uploading several photos from a recent hike and I wasn't successful until I converted them to JPEG. 

Is that an understood limitation or did I miss a configuration option? 

Thanks!

**Comment by Flomp** [comment]
Hi there,

thanks for the hint. This is fixed in v0.8.2.
