### ISSUE TITLE
Trails Page:  500 Internal Error (when private trails / logged in)

### ISSUE THREAD

**Issue by gitmotion** [Flomp/wanderer#112]
First off great project! love it and used it on my last trip to plan out some hikes, worked perfectly. I just came back to it after and noticed that the trails page was giving me a 500 error. This error does not happen when a trail is public and viewed when not logged in. however i cannot view trails when logged in, preventing me from viewing non-public trails

i checked the logs for each container and everything looked fine however when looking at the logs for the web container i was seeing this when hitting the search page: (strange because it was working just fine and now im getting an invalid API key error)
![image](https://github.com/user-attachments/assets/d404c7fe-1edd-4476-848d-a7c2085f14f1)

side note: i tried exporting the trails and importing them on a fresh install. the search page works again but the trails do not have their way points retained even with a full export. anyone run into this? seems like something with the MeiliSearchApi?

![image](https://github.com/user-attachments/assets/2b0a4118-d82e-41f7-94db-f8b77f235738)
- not sure if this is correct but when logged out we get a public search token and when not logged in it tries to grab a token from the pb.authstore. maybe something wrong with passing the pb.authstore token to the new meili request?

**Comment by gitmotion** [comment]
just exported all the trails from settings, downloaded all the .gpx files from pb web ui, then had to redeploy, import, and replace the gpx files for each trail to retain the maps. would be nice if the export/import properly mapped the map points. maybe im doing something wrong there when exporting?

**Comment by Flomp** [comment]
Hi,

thanks for your issue report. Your original issue seems to be that your Meilisearch API key was somehow invalid. The token is stored alongside your other account data in pocketbase and gets read in the lines you posted above. It's unfortunately not really possible for me to reconstruct how exactly this happened. 
If this happens again (e.g. after another streak of longer inactivity) I'll need to see if I can reliably recreate the problem.

Regarding your export/import question: it is currently not possible to fully restore a trail by importing it from a GPX file. Neither GPX and GeoJSON file formats are capable of handling the rather complex data structure that wanderer uses for its trails (waypoints, summit logs, photos, shares, lists etc.). It is on my roadmap to create a file format that allows to store all this information and enable users to fully export and import trails without losing data.

**Comment by gitmotion** [comment]
thanks for your response! good to know for next time if i ever run into that issue and thank you for the update on the export files. i think for now the best approach i found was creating a pocketdb backup when it's in a stable state and restoring from that .zip file if it ever goes down again. will let you know if i ever run into that situation again 🙏
