### ISSUE TITLE
On gpx file upload, set trail name to filename 

### ISSUE THREAD

**Issue by jo-chemla** [Flomp/wanderer#114]
This would be useful both for single trail upload as well as multi, batch file uploads. Could also eventually fallback to track name within the gpx, but usually less used.

**Comment by githubhacs** [comment]
I'll vote against this behaviour. 
All my GPX files have names that completely differ from the filename.

**Comment by jo-chemla** [comment]
Alright, thanks for commenting. This could be left as a choice for the user on import, to either use gpx file name or track name. Default behavior could be the current one, at least while there is still more traction for it, and a CLI or UI flag could be passed for those that prefer using filenames over track names.

**Comment by Flomp** [comment]
I agree with @githubhacs here. The GPX name should be prioritized over the filename. I changed the naming scheme fallbacks to look like this: GPX name -> File name -> Generic name (trail-dd-MM-yyyy). 
I think that is a good compromise.

**Comment by jo-chemla** [comment]
Thanks, indeed probably a good compromise!

**Comment by Flomp** [comment]
Added in v0.10.0.
