### ISSUE TITLE
Display share URL instead of copy only

### ISSUE THREAD

**Issue by thomas-mc-work** [Flomp/wanderer#117]
Currently there is the feature to copy a share URL. But my instance is running in an internal network with HTTPS support, so some JavaScript APIs are disabled in the browser by design (e.g. to use the clipboard). This is fine so far, but it would be nice to get the link in any other subtle way. Preferable without cluttering the interface. Maybe by opening the link via <kbd>shift</kbd> + click.

![image](https://github.com/user-attachments/assets/75e52a8b-d78b-4251-9c46-9f501573406f)

**Comment by Flomp** [comment]
I see. The URL you copy is simply the one displayed in your browser's address bar. So you could just copy it from there.

**Comment by thomas-mc-work** [comment]
The location is just `http://wanderer.lan/lists`, no list identifier in there.

**Comment by thomas-mc-work** [comment]
Well … I think the request is useless anyway because there is no need to share when hosting it internally.
