### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by Thovi98** [Flomp/wanderer#118]
First of all, thanks and congrats for this great app! I like the UI and the new profile page is awesome.

I’ve [packaged](https://github.com/YunoHost-Apps/wanderer_ynh/) the app for [Yunohost](https://yunohost.org/) and it works great!

Some little issues/suggestions:
- The API documentation link at the bottom of the page is broken, because it tries to open `domain.tld/wanderer.to/api-reference/auth` (it’s reproductible on the demo instance)
- I’ve read [this issue](https://github.com/Flomp/wanderer/issues/4) about the max photos/gpx size and I find the 5MB a bit low: lots of photos have a higher size. I would change the max to 20MB, but it’s my two cents ;) 
- I didn’t see how to go to the profile page on Android with Firefox because it is hidden by the address bar:
![photo_2024-11-07_17-55-38](https://github.com/user-attachments/assets/b147c846-d062-4cb3-a156-046128d5aa1c)

Thank you :D

**Comment by Flomp** [comment]
Wow, I didn't know YunoHost yet. Great project! Thanks for adding wanderer.

- URL is now fixed in v0.10.1
- I still find it easy enough to set the size on your own in PocketBase as described in the issue
- This now also fixed in v0.10.1. Thanks for the hint.

**Comment by Thovi98** [comment]
Nice, thank you!
