### ISSUE TITLE
[cosmetic] Settings:Default Location does not "stick"  at first

### ISSUE THREAD

**Issue by asitemade4u** [Flomp/wanderer#12]
1. Click on the user icon on the main page > Settings
2. I type `new y` in the Default Location
3. a popup menu shows the cities and I choose `New York City`
4. However, the value is not transferred to the field, which remains as `new y`

**Comment by Flomp** [comment]
Thanks for pointing that out. Will be fixed in the upcoming patch.

**Comment by Flomp** [comment]
Should now be resolved in v0.1.1
