### ISSUE TITLE
[Feature] Filter Trails by User

### ISSUE THREAD

**Issue by tofublock** [Flomp/wanderer#120]
Wow, this project looks really good! Saw your post on Lemmy yesterday and gave it a go and it's really good-looking and useful already.

One thing I noticed is that it's not easy to see who created a trail. Public trails show up for all users, with no option to only look at your own trails. If I'd want to do an evening bike ride from home and want to quickly pick "one of my usual routes" by specs, that would be hard to do with foreign trails in there.
Moreover, the "completed" attribute becomes meaningless for public trails, since trails show as completed for everybody as long as there's something in the summit book, so that doesn't help with filtering them down either. (Did I see that right? Somewhat related to #99.)

What would solve the first issue very nicely and make it easier to share trails between multiple users would be some indicator who created the trail (display user name with public trails), and then a way to filter down the trails by user: You could still start out with a list that shows all your own trails and also all the public ones, but allow to filter by creator (just me, just public, specific other user, or maybe even a combination of users.)
Then if you add the information which user logged a summit, the "completed" info becomes meaningful again and that would also be a really cool way for users to engage with each other.

What do you think?

**Comment by Flomp** [comment]
Good idea. I'll include it in the next minor version.

**Comment by Flomp** [comment]
This is now available in v0.11.0

**Comment by tofublock** [comment]
This is perfect. Great work.
