### ISSUE TITLE
Distance =  0 km

### ISSUE THREAD

**Issue by TheNomad11** [Flomp/wanderer#121]
Whenever I upload a gpx file, both in my selfhosted instance or on the demo at https://demo.wanderer.to/profile  the distance in the statistics page is zero km. I suppose it isn't supposed to be like this?

**Comment by Flomp** [comment]
If you did not create a trail via the UI interface, but rather uploaded it directly (via Settings -> Import) currently no summit log is automatically created. This is a bug and will be fixed in the next patch. The statistics are created from summit logs, not the trail itself.

**Comment by TheNomad11** [comment]
I clicked on "New trail" and then upload. There is a summit book entry that looks like this:

![screen-2024-11-09-11-46-49](https://github.com/user-attachments/assets/632371d6-8e48-4e27-82c9-d40e24f4cece)

**Comment by Flomp** [comment]
Ah, that seems to be an issue with how I calculate the totals for the summit logs. Would you mind providing the GPX file? Either here, or. upload it on the demo instance.
Thanks!

**Comment by TheNomad11** [comment]
It is in the demo instance https://demo.wanderer.to/trail/view/nkz1wglmsv7dzhx

**Comment by Flomp** [comment]
Fixed in v0.10.1.

**Comment by TheNomad11** [comment]
Wow, so fast! Thanks a lot! Looking forward to the release!
