### ISSUE TITLE
Translation issue in the category

### ISSUE THREAD

**Issue by update-freak** [Flomp/wanderer#127]
Hi developer,

I found a translation issue for the german language.
In the category it says "Hiking" instead of "Wandern".
You can see it in the picture below:

![pic](https://github.com/user-attachments/assets/84ff233b-9322-4348-a910-8e0ad6eb59e3)

Version: v0.10.0
device: Synology NAS with Docker

**Comment by Flomp** [comment]
Thanks, will be fixed in v0.10.2.
