### ISSUE TITLE
Search container will not start

### ISSUE THREAD

**Issue by phil3741** [Flomp/wanderer#129]
The search container is always unhealthy when using the docker-compose method on Raspberry Pi 64 bit.

Tried:
pulling the current docker-compose.yaml
Addinf "platform: linux/arm64/v8" to the containers specifications
docker-compose up -d

The containers get pulled successfully and all other containers start sucessfully, except the search container. There are no logs available other than "wanderer-search exited with code 159"

I have found no documentation on this issue and assume it should work on Raspberry Pi since the arm v8 Containers are available.

**Comment by Flomp** [comment]
The search container is definitely build both for amd64 and arm64. It also runs perfectly fine on my Raspberry Pi. So I suspect there must be something else going on there. Can you try and run a raw meilisearch container on your system?

`docker run -it --rm \
  -p 7700:7700 \
  getmeili/meilisearch:v1.11`

**Comment by phil3741** [comment]
The raw meilisearch container won't start either.

The command
`docker run -it --rm -p 7700:7700 getmeili/meilisearch:v1.6.2`
itself does not work:

```
$ docker run -it --rm -p 7700:7700 getmeili/meilisearch:v1.6.2
Unable to find image 'getmeili/meilisearch:v1.6.2' locally
v1.6.2: Pulling from getmeili/meilisearch
docker: no matching manifest for linux/arm/v8 in the manifest list entries.
See 'docker run --help'.
```

The command
```
$ docker run --platform linux/arm64/v8 -p 7700:7700 getmeili/meilisearch:v1.6.2
Unable to find image 'getmeili/meilisearch:v1.6.2' locally
v1.6.2: Pulling from getmeili/meilisearch
550f8bf8502c: Already exists
b90078615c50: Already exists
bfd0d1b0c34d: Already exists
c8d553abd6a0: Already exists
62607d24812d: Already exists
e5d6a08d796e: Already exists
Digest: sha256:634e83ffe5bad15239fa26bd04d06bccb84a1f2f06ad8a35135b510711348792
Status: Downloaded newer image for getmeili/meilisearch:v1.6.2
$
```

exits without any logs but the container has not started. I'm not sure what could cause this or if this could be a misconfiguration on my side. `uname -m` yields `aarch64`, so arm64/v8 should be correct, right?

**Comment by phil3741** [comment]
ok I am 99% sure this is a configuration error of docker on my side as it has the armhf repository installed while it should be arm64. I will report back once I fixed it, but otherwise this can be closed
