### ISSUE TITLE
[improvement] City search results in the U.S. should include State

### ISSUE THREAD

**Issue by asitemade4u** [Flomp/wanderer#13]
So, as I live in NYC, I have input several trails walked in Brooklyn.

1. I input `brooklyn` in the search field
2. I get a list of my trails, fine
3. but I also get two `Brooklyn` in the U.S. without any means to know where they are as the State is not included > please include State.

**Comment by Flomp** [comment]
Good hint! I am currently using [this](http://download.geonames.org/export/dump/) public dataset. Unfortunately they split the state name into a separate textfile. Not terrible but it will require some manual stitching to get all the necessary information in the search index. I'll probably add in the next minor version.

**Comment by Flomp** [comment]
With the new release v0.2.0 search results now include the province/state of the city. Please note that you must delete your `data.ms` folder for this change to work. The meilisearch indices will be rebuilt when you start wanderer again.
