### ISSUE TITLE
"404 Not found" when a public track is opened

### ISSUE THREAD

**Issue by update-freak** [Flomp/wanderer#133]
I changed a track to public and then I tried to open the details of this track when I was not logged in.
After clicking on the track name I got a "404 Not found" (see screenshot below).

![Screenshot_20241126_213910_Chrome](https://github.com/user-attachments/assets/548d1fab-6952-4cda-9fe4-a9d9f030c637)

Version: v0.11.0

**Comment by Flomp** [comment]
Hi there,

that is unfortunately very hard to debug with the information you provided. Could you please provide some steps to reproduce the issue? Ideally starting from a fresh install.

**Comment by update-freak** [comment]
yes, sure.
0) Login
1) Import a GPX-file
2) Edit the track and change public to enabled
3) Logout
4) Go to tracks and you will see the track which you set to public
5) Try to open that track
6) you will get a 404 Not Found error

**Comment by update-freak** [comment]
I tried it again with the new release v0.12.0.
There I did not have this problem.
Therefore I close this issue.
