### ISSUE TITLE
main branch not stable: map_with_elevation_maplibre.svelte

### ISSUE THREAD

**Issue by gri38** [Flomp/wanderer#134]
Hi.

From this commit: efe3b3bf878ca45fc1d85303cf2c7f9354eeb8ee (02/12/2024 01:46:29)
On file web/src/lib/components/trail/map_with_elevation_maplibre.svelte

      const preferredMapStyleIndex = mapStyles.findIndex(
          (s) => s.text === localStorage.getItem("layer"),
      );

With that code I have preferredMapStyleIndex  == -1
so `mapStyles[preferredMapStyleIndex].value ?? ` fails.

Can it be fixed... I'm trying to porpose a PR about #130 .

@Flomp What about having a discord to discuss between developers?

**Comment by Flomp** [comment]
Sorry, it's fixed now. I'm not used to other people working on the main branch yet.
Let me know in case you run into other issues. I'm currently rewriting a large part of the map logic. So there might be other breaking changes.

Discord: [https://discord.gg/MdpybUHc](https://discord.gg/MdpybUHc)
