### ISSUE TITLE
Unable to register new user

### ISSUE THREAD

**Issue by miherrm** [Flomp/wanderer#14]
I just deployed the stack via the provided docker-compose.yml on my Synology, adjusting the 'volumes' settings were the only changes I made. The deployment went fine, the frontpage is showing up.

Unfortunately it is not possible to register a user. Error message "Fehler beim Erstellen des Nutzers"

**Comment by manwec** [comment]
Seconded.

Tried it in an existing VM through Portainer and on a new VM running debian and docker without Portainer.
This is the output of the console when I hit register:
![Bildschirmfoto](https://github.com/Flomp/wanderer/assets/96175020/85ae4ece-fced-49eb-aef4-e5cdc70558cd)

Everything entered normally of course, just redacted after the fact.

**Comment by berilslv** [comment]
yes im facing the same.
Ubuntu 22.04-> fresh vm+ fresh docker.
is there any default user which can be used for first time use?

**Comment by Flomp** [comment]
Hey,

that is strange. I have not been able to replicate the problem so far. For me, the default docker-compose works both on an Ubuntu 23.04 x86_64 VM and a Debian 12 arm64 RaspberryPi.

Is there any json data attached to the 403 error response?
Could you please post your docker-compose file? Maybe I can replicate the issue that way.

**Comment by manwec** [comment]
> Hey,
> 
> that is strange. I have not been able to replicate the problem so far. For me, the default docker-compose works both on an Ubuntu 23.04 x86_64 VM and a Debian 12 arm64 RaspberryPi.
> 
> Is there any json data attached to the 403 error response? Could you please post your docker-compose file? Maybe I can replicate the issue that way.

I've not changed much in the docker-compose file.
Here's my docker-compose.yml:

`version: '3'

x-common-env: &cenv
  MEILI_URL: http://search:7700
  MEILI_MASTER_KEY: CHANGE_ME!

services:
  search:
    container_name: wanderer-search
    image: flomp/wanderer-search
    environment:
      <<: *cenv
      MEILI_NO_ANALYTICS: true
    ports:
      - 7700:7700
    networks:
      - wanderer
    volumes:
      - ./data/data.ms:/meili_data/data.ms
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
  db:
    container_name: wanderer-db
    image: flomp/wanderer-db
    depends_on:
      search:
        condition: service_healthy
    environment:
      <<: *cenv
    ports:
      - "8090:8090"
    networks:
      - wanderer
    restart: unless-stopped
    volumes:
      - ./data/pb_data:/pb_data
  web:
    container_name: wanderer-web
    image: flomp/wanderer-web
    depends_on:
      search:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      <<: *cenv
      ORIGIN: http://localhost:3000
      PUBLIC_POCKETBASE_URL: http://db:8090
    ports:
      - "3000:3000"
    networks:
      - wanderer
    restart: unless-stopped

networks:
  wanderer:
    driver: bridge`

Here's my setup:

- Proxmox 8.1.4 on bare metal (Intel-based server)
- Created a new VM based on this debian image: debian-12.5.0-amd64-netinst.iso
- Updated the VM
- installed a root account and a wanderer-user-account
- In the wanderer-account, I installed docker through terminal with the commands listed here: https://docs.docker.com/engine/install/debian/
- Created a directory "wanderer"
- Got the docker-compose-file with your instruction: wget https://raw.githubusercontent.com/Flomp/wanderer/main/docker-compose.yml
- Checked the file, I think I didn't change anything this time
- did docker compose up -d
- Got no errors at all during installation, got all three containers up and running, see here: 
![grafik](https://github.com/Flomp/wanderer/assets/96175020/9d4a4f5a-a1cb-4205-9827-0a24ffc52b5a)

**Comment by Flomp** [comment]
Thanks for the detailed debug info. Could you please head 192.168.178.132:8090/_/ make an admin account and see if the collections (database tables) are there?
Also, does the 403 error response give any json back?

**Comment by manwec** [comment]
> Thanks for the detailed debug info. Could you please head to 192.168.178.132:8090/_/ make an admin account and see if the collections (database tables) are there? Also, does the 403 error response give any json back?

Sure. All collections are empty except for the categories:
![grafik](https://github.com/Flomp/wanderer/assets/96175020/98fa1f8d-08b5-45ed-b323-d7239c43d618)

Here's more info on the 403 error:
![grafik](https://github.com/Flomp/wanderer/assets/96175020/c3b47324-3d8a-4fb8-9f00-bac55949e7c0)

and

![grafik](https://github.com/Flomp/wanderer/assets/96175020/f8659691-a485-4e78-8db1-20d8f3270811)

Hope this helps.

**Comment by Flomp** [comment]
Ah, there we go. You need to set your ORIGIN variable in your docker compose file to the host address that you are actually hosting wanderer at.
So in your case http://192.168.178.132:3000 I assume?

**Comment by manwec** [comment]
> Ah, there we go. You need to set your ORIGIN variable in your docker compose file to the host address that you are actually hosting wanderer at. So in your case http://192.168.178.132:3000 I assume?

That was it. Could successfully register now. Should have caught it myself to be honest. Thanks!

**Comment by miherrm** [comment]
> Ah, there we go. You need to set your ORIGIN variable in your docker compose file to the host address that you are actually hosting wanderer at. So in your case http://192.168.178.132:3000 I assume?

Perfect, that did the job. Thanks for pointing this out.

**Comment by berils** [comment]
I can confirm, that after chaing ORIGIN value to IP address of host, I can get in.
Thanks Flomp! This project looks very promising! :)

**Comment by Flomp** [comment]
Great! Happy to hear that it did the trick. I'll close this for now.

**Comment by B0rax** [comment]
Just a heads up, as I ran into the same issue, maybe add that hint to the Readme? not only that the port must be correct, but also the IP address should be included there.
