### ISSUE TITLE
Your database version (1.6.2) is incompatible with your current engine version

### ISSUE THREAD

**Issue by thomas-mc-work** [Flomp/wanderer#143]
Hello!

After the update from version `0.11.0` to `0.12.0` I got this error on startup:

    2024-12-08T17:45:03.834406Z ERROR meilisearch: error=Your database version (1.6.2) is incompatible with your current engine version (1.11.3).
    To migrate data between Meilisearch versions, please follow our guide on https://www.meilisearch.com/docs/learn/update_and_migration/updating.

I took a look at the link with the guide but I hope this isn't the path I have to go. Maybe you could provide a script that does this migration? Ideally without being dependant on an API key which I haven't created prior to the update.

**Comment by Flomp** [comment]
Please read the [changelog](https://github.com/Flomp/wanderer/blob/main/CHANGELOG.md).
