### ISSUE TITLE
[Doc] Incorrect Meili Master Key Documentation

### ISSUE THREAD

**Issue by elmodor** [Flomp/wanderer#15]
Hi,

The documentation of the meili master key for the docker-compose setup is incorrect.
The key _has to be changed_ to a secure key (I don't know what the security parameters are for meili)

When setting an insecure key, the wanderer-search container log contained the following:
```
A master key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.


 Meilisearch started with a master key considered unsafe for use in a production environment.

 A master key of at least 16 bytes will be required when switching to a production environment.


We generated a new secure master key for you (you can safely use this token):

>> --master-key ALongKey <<
```
The new master key was a 42 character string.

The issue here is, with my insecure key I was not able to use meili search. After uploading some GPX tracks, the Trails and Map view did not contain any tracks. They were only shown on the Home screen.

I had to delete the data folder, and set a secure key for meili to be able to see the gpx tracks in the Trails and Map view.

A secure key can for example be generated via:
`openssl rand -hex 22`

**Comment by Flomp** [comment]
Thanks for pointing it out. I adjusted the documentation and default docker-compose.yml accordingly.
