### ISSUE TITLE
[Feature] Map View Adjusted to Tracks

### ISSUE THREAD

**Issue by elmodor** [Flomp/wanderer#16]
Hi,

it would be nice if the there is an option for the Map view so that the map is automatically adjusted based on the location of all tracks.

E.g. independent from the default location, the map is zoomed and adjusted so that all tracks of the user is visible in the map.

This would allow the user to automatically see all of their tracks at once on the map without having to zoom out/in / pan around.

**Comment by Flomp** [comment]
I just published v0.4.0. You now have an option in your profiles page to make the map focus on your trails instead of a specific location.
