### ISSUE TITLE
Only max 5 tracks are ever shown

### ISSUE THREAD

**Issue by WetenSchaap** [Flomp/wanderer#17]
First of, loving this project, I've been looking for something like this for a while! 

I noticed when I uploaded a bunch of gpx files to test things out, the _trails_ tab of wanderer only ever shows  the first 5 tracks matching filter criteria. So if there are more than 5 tracks, they are simply not shown. 

If you change the ordering (to e.g. alphabetical), 5 different tracks will be shown, so it is not an error in uploading, etc.

The same happens in the _Map_ tab. Interestingly, it does not seem to be a problem in the _Lists_ tab.

I am just using the default docker-compose. No changes.

**Comment by Flomp** [comment]
Ah, I forgot to set the default per-page value in the web API. This will be fixed in the next patch. Thanks for pointing it out!

**Comment by Flomp** [comment]
I just released v0.1.1. The issue should be resolved now.

**Comment by WetenSchaap** [comment]
I can confirm it works now, thanks!

**Comment by Flomp** [comment]
Perfect, then I will close this for now!
