### ISSUE TITLE
[improvement] units (mi/ft) should be a user setting and same over all pages

### ISSUE THREAD

**Issue by bergziege** [Flomp/wanderer#18]
As a user with a german Browser and an english server I am getting mixed distance/elevation units in the ui.
- mi/ft on the front page (in the tiles)
- km/m on the map

Improvement:
- Would be nice if the same units could be used on all pages.
- Would be nice if the user could select between imperial and metric units.

**Comment by Flomp** [comment]
You can change your preferred units in your profile settings. Click your avatar in the navbar and select "Profile". Does that resolve the consistency issues?

**Comment by bergziege** [comment]
Whoops, totally overlooked that.

Solves this problem perfectly!
