### ISSUE TITLE
I can't seem to be able to log out and can't edit avatar

### ISSUE THREAD

**Issue by ovizii** [Flomp/wanderer#19]
Nothing to be seen in the docker logs or in the browser console.
Repeatedly trying to log out, I see some weird icons:

![image](https://github.com/Flomp/wanderer/assets/837902/39ac2230-bef9-45a2-95e3-cf85473b0530)

I click on my profile, on the avatar, select a local file, nothing happens. No errors either.

**Comment by ovizii** [comment]
Hm, I've put wanderer behind an internal reverse proxy, just for the https and the pretty URL and now logging out works. 

Still no luck with the avatar.

**Comment by Flomp** [comment]
Good find, that functionaliry didn't survive my recent API refactoring. Will be fixed with the next patch.

**Comment by berils** [comment]
> Hm, I've put wanderer behind an internal reverse proxy, just for the https and the pretty URL and now logging out works.
> 
> Still no luck with the avatar.

Can you share your npm config? When i was trying to set it after NPM, im getting error:
![image](https://github.com/Flomp/wanderer/assets/12886866/e5d6c177-f3b1-45ee-a194-10e0bcf47fbe)

**Comment by ovizii** [comment]
I'm using traefik, so I doubt this will help you. 
I set up traefik years ago. All I need to reach new containers is to add these labels to them, change URL, port and the name of the network to make sure traefik can reach this container.

```
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_wanderer"
      - "traefik.http.routers.wanderer.tls=true"
      - "traefik.http.routers.wanderer.entrypoints=websecure"
      - "traefik.http.routers.wanderer.rule=Host(`trails.int.domain.tld`)"
      - "traefik.http.routers.wanderer.middlewares=secHeaders@file"
      - "traefik.http.routers.wanderer.service=wanderer"
      - "traefik.http.services.wanderer.loadbalancer.server.port=3000"

```

**Comment by Flomp** [comment]
> > Hm, I've put wanderer behind an internal reverse proxy, just for the https and the pretty URL and now logging out works.
> > Still no luck with the avatar.
> 
> Can you share your npm config? When i was trying to set it after NPM, im getting error: ![image](https://private-user-images.githubusercontent.com/12886866/313710452-e5d6c177-f3b1-45ee-a194-10e0bcf47fbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODc0MjUsIm5iZiI6MTcxMDc4NzEyNSwicGF0aCI6Ii8xMjg4Njg2Ni8zMTM3MTA0NTItZTVkNmMxNzctZjNiMS00NWVlLWExOTQtMTBlMGJjZjQ3ZmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE4Mzg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Y2VhODcxNjE4MzQ0M2E4YzI0M2FjNDIzMDI4OGMxYThmMjU2ZWYzZDJjZTcwOWNjN2E0MDk3NjFjOGQ4NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYnO8YfYHoLTuR46vZzvY6eP41T4KwNMxIEqd9c5Pnk)

Have you set your ORIGIN env var to the correct URL? Also, if this is about changing the avatar, I'm afraid this doesn't work yet. The patch will be published soon, though!

**Comment by berils** [comment]
> > > Hm, I've put wanderer behind an internal reverse proxy, just for the https and the pretty URL and now logging out works.
> > > Still no luck with the avatar.
> > 
> > 
> > Can you share your npm config? When i was trying to set it after NPM, im getting error: ![image](https://private-user-images.githubusercontent.com/12886866/313710452-e5d6c177-f3b1-45ee-a194-10e0bcf47fbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODc0MjUsIm5iZiI6MTcxMDc4NzEyNSwicGF0aCI6Ii8xMjg4Njg2Ni8zMTM3MTA0NTItZTVkNmMxNzctZjNiMS00NWVlLWExOTQtMTBlMGJjZjQ3ZmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE4Mzg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Y2VhODcxNjE4MzQ0M2E4YzI0M2FjNDIzMDI4OGMxYThmMjU2ZWYzZDJjZTcwOWNjN2E0MDk3NjFjOGQ4NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYnO8YfYHoLTuR46vZzvY6eP41T4KwNMxIEqd9c5Pnk)
> 
> Have you set your ORIGIN env var to the correct URL? Also, if this is about changing the avatar, I'm afraid this doesn't work yet. The patch will be published soon, though!

Thanks for your quick responses!
Yes I changed  ORIGIN to NPM domain name http://wanderer.mydomain.com (tried with and without http/https) still im getting error.
Maybe problem is proxy, as if I access page with local IP, I don't get login/create user/etc. errors.

![image](https://github.com/Flomp/wanderer/assets/12886866/085ee0ab-aa0b-4e59-9fdf-32797f0b7a92)

**Comment by Flomp** [comment]
Could you please post the JSON that the 403 response returns (if any)?

**Comment by berils** [comment]
> Could you please post the JSON that the 403 response returns (if any)?

I don't know if I understood you correctly, but I will refer each POST failure part. If further information required, let me know:
       POST https://wanderer.mydomain.com/api/v1/auth/login 403 (Forbidden)
window.fetch @ entry._nIRiqSn.js:1
![image](https://github.com/Flomp/wanderer/assets/12886866/d3d2b542-2056-4911-83bf-101d7576c877)

oe @ user_store.zU2SoMYk.js:1
![image](https://github.com/Flomp/wanderer/assets/12886866/2af01d4e-8d86-484a-8a10-fa3a2365b8e7)

onSubmit @ 4.K1iGa8JJ.js:1
![image](https://github.com/Flomp/wanderer/assets/12886866/330a1033-f0e8-4565-95f7-26c392be69af)

(anonymous) @ create-form.7uS7Ma6_.js:1
![image](https://github.com/Flomp/wanderer/assets/12886866/e885ec82-df0c-4565-b56c-c311d8c6ce99)

Promise.then (async)
V @ create-form.7uS7Ma6_.js:1
![image](https://github.com/Flomp/wanderer/assets/12886866/396ad048-1214-4385-8f4d-e157e217e899)

(anonymous) @ create-form.7uS7Ma6_.js:1
Promise.then (async)
![image](https://github.com/Flomp/wanderer/assets/12886866/43dc904c-0b13-4839-9659-ceeac4d9f48b)

(anonymous) @ create-form.7uS7Ma6_.js:1
Promise.then (async)
x @ create-form.7uS7Ma6_.js:1
![image](https://github.com/Flomp/wanderer/assets/12886866/24a0b3ab-2fa8-4785-8d19-8542f4c8a9f8)

**Comment by Flomp** [comment]
Thanks. I'd be interested in what the actual response from the request to https://wanderer.mydomain.com/api/v1/auth/login is. Is it a plain error message or JSON?

**Comment by berils** [comment]
> Thanks. I'd be interested in what the actual response from the request to https://wanderer.mydomain.com/api/v1/auth/login is. Is it a plain error message or JSON?

Sorry for late reply,
here it is:
![image](https://github.com/Flomp/wanderer/assets/12886866/12167a14-c42e-4740-864f-9d119e92d7c3)

**Comment by Flomp** [comment]
But now you opened the API endpoint directly in your browser, right? This will not work because - as the error suggests - the endpoint does not support GET requests. I'm interested in what the answer from the server is when you press the login button. 
![wanderer_login2](https://github.com/Flomp/wanderer/assets/26000991/8cff6bda-e5cd-4446-9ca1-cc953eb80eaa)

Please excuse my German browser (and the fact the login for me of course works), but I hope the idea is still clear.

**Comment by Flomp** [comment]
Moved to #53.
