### ISSUE TITLE
[Feature suggestion] Auto-upload folder for gpx files

### ISSUE THREAD

**Issue by berils** [Flomp/wanderer#23]
Good morning,

Im sorry if these feature requests are too much, but....
It would be cool feature if there we're option to upload files automatically using syncthing,nextcloud sync, rsync, or any other sync software.

Scenario: Im getting on my bike, with open osmand, which automatically start to record trail. After I finish my ride, I press save button and add comments. This file is being saved in folder TRACKS, and this folder is synced to wanderer folder TRACKS.

Now only option is to manually upload gpx files, but it would be awesome if this gpx file repository would be up-to-date all the time with tracking device. Not necessary both ways, but it would be cool if they were imported automatically.

Now storage tree looks like this:
![image](https://github.com/Flomp/wanderer/assets/12886866/9024b0d8-fa5f-4e37-a7e3-ed6d0f879494)

BR,
Berils

**Comment by Flomp** [comment]
I really like this idea. I will likely finish proper API support for trail uploading first as that has been requested a lot. However, I have put it on the [roadmap](https://github.com/users/Flomp/projects/2).

**Comment by Flomp** [comment]
Added in v0.3.0. Please refer the [docs](https://github.com/Flomp/wanderer/wiki/API#auto-upload-folder) for more details.
