### ISSUE TITLE
External auth with OIDC/Oauth2?

### ISSUE THREAD

**Issue by poVoq** [Flomp/wanderer#24]
Would be nice if it were possible to configure an easy to use login provider via Oauth2/OIDC.

That way it would be for example easy to integrate accounts with a Mastodon instance or similar.

Pocket base seems to have support for this: https://pocketbase.io/docs/authentication#oauth2-integration

Thanks for considering this.

**Comment by Flomp** [comment]
I agree, it would be rather simple I think. However, I would like wanderer to stay unopinionated about which OAuth providers it supports as users preferences surely vary. I will need to think about how to make the different providers configurable in the frontend through environment variables (?) or another way of configuration.

**Comment by Flomp** [comment]
Added in v0.3.0. Please refer to the [docs](https://github.com/Flomp/wanderer/wiki/OAuth) for more info.

**Comment by poVoq** [comment]
Looks excellent. Thanks for adding this. I think we can close this issue then.
