### ISSUE TITLE
Dates for Summit Book entries are recorded incorrectly

### ISSUE THREAD

**Issue by mmanjos** [Flomp/wanderer#29]
It appears that something is shifting the date entered in "Summit Book" entries:

What's entered in the dialog:
![image](https://github.com/Flomp/wanderer/assets/3483684/54537e22-355e-4bb7-acf2-dcb407b510eb)

What's saved:
![image](https://github.com/Flomp/wanderer/assets/3483684/201bdbe3-b9c6-45ce-89aa-614b02fc9068)

Attempting to edit the date afterwards does not fix the entry.

Browser: Firefox 123.0.1 on Arch
Locale: en_US

**Comment by mmanjos** [comment]
Another example, using today's date on an entry where I did not touch the pre-filled dialog box:
![image](https://github.com/Flomp/wanderer/assets/3483684/4fd29cbf-9b93-4d71-94e9-0b97ea023203)

and saved:

![image](https://github.com/Flomp/wanderer/assets/3483684/68e18c16-34aa-4d10-98f4-63f69c50690f)

**Comment by mmanjos** [comment]
It might be shifting the date back by 2 days each time?

**Comment by Flomp** [comment]
I can't seem to replicate the problem. I did however notice that I hardcoded the German date formatting. I fixed this for the next version so that dates are now displayed in your local formatting. Maybe this will also fix your issue. It will be included in the next patch.

**Comment by mmanjos** [comment]
Thanks! I'll be sure to test it as soon as it gets released and report back.

It's definitely a strange one - I've been trying to step through the code and find out what's going on but no luck so far. It also happens in chrome, for what it's worth.

Here's a capture of the experience - every time the date is saved in browser (before the trail is saved), the date "walks" backwards by 2 days it seems:

![bug](https://github.com/Flomp/wanderer/assets/3483684/2731a43e-73ae-47cd-8dc0-5246d68f0991)

**Comment by mmanjos** [comment]
Interesting... it definitely seems related to locale-settings. If I start up a fresh Ubuntu VM and change the date format to German, the bug does not happen any longer:
![image](https://github.com/Flomp/wanderer/assets/3483684/5a3de016-d917-48ad-9207-30741bc8d229)

**Comment by mmanjos** [comment]
Interesting... hopefully this helps narrow it down some more. 

It appears that the date "shift" problem happens in the edit dialog regardless if the entry is saved or not.

Here's what happens if I keep opening up the same entry and just click `Cancel` each time:
![bug3](https://github.com/Flomp/wanderer/assets/3483684/418afd87-b477-4a87-80bc-08594466aa64)

**Comment by mmanjos** [comment]
It looks like this comment on an upstream issue describes the problem I'm encountering:

https://github.com/sveltejs/svelte/issues/7337#issuecomment-1058358626

**Comment by Flomp** [comment]
I could replicate and fix the bug. It was indeed a timezone issue combined with the date formatting function. That was a tricky one...
Thanks for your help! It will be fixed with the next minor version.

**Comment by mmanjos** [comment]
Glad to help - and very thankful for this awesome project you've put together.

I wish I could help with the code / suggest some PRs but my background is more go/python. Getting into Sveltekit / TS and browser-side code is intimidating :)

**Comment by Flomp** [comment]
Hopefully fixed with v0.3.0.

**Comment by mmanjos** [comment]
It looks like v0.3.0 has fixed the issue with the date shifting each time it's edited, but the initial date still seems to be recorded incorrectly on a "save".

For example, today if I enter a Summit Book entry with 3/31/2024, it saves as 3/30/2024. If I then go to edit that entry, it displays 3/31/2024 in the edit modal, but goes back to 3/30/2024 once it's saved.

So maybe now it's just the code that displays the date on the normal trail details page and not the edit pop-up modal?

**Comment by Flomp** [comment]
Argh, I hate dealing with dates & timezones...
I think I have now fixed it now by setting the timezone to UTC. Will be included in the next version (v0.4.0).

**Comment by Flomp** [comment]
I published v0.4.0 which hopefully fixes the problem now.

**Comment by mmanjos** [comment]
Apologies for the late reply. Looks good! I just did a bunch of testing on v0.4.0 and this bug appears fixed now! Many thanks!
