### ISSUE TITLE
Existing trail Name and Description are reset on edit

### ISSUE THREAD

**Issue by mmanjos** [Flomp/wanderer#30]
Even if there's already a description saved in the database for a trail, the "Describe your trail" field is always empty when editing:

![image](https://github.com/Flomp/wanderer/assets/3483684/60ba4f31-77d3-4e35-a9d5-06d20f24bc51)

**Comment by mmanjos** [comment]
I think what might be happening here is that the blank description string in my imported GPX always takes precedence, even if I've already edited and saved a different description inside wanderer

**Comment by mmanjos** [comment]
Yeah, it seems like most of the fields (including the trail Name) are being reset to whatever value happened to be in the GPX file upon import.

**Comment by Flomp** [comment]
Yes, this is the intended behaviour. I think it is more intuitive for the user if the form resets when you upload a new file. I can however see that this can be frustrating if you fill everything in and then upload a file subsequently deleting all your information. So maybe it would be an idea to disable everything else until a file is uploaded?

**Comment by mmanjos** [comment]
In this case, I don't think I was uploading a new GPX file each time. My workflow was:

1. Upload a GPX file that I had exported from my phone
2. Save the trail
3. Go back and edit the trail after it was initially saved: give it a different trail name and add a description
4. Save the trail - at this point, my custom name and description are persisted and display correctly
5. Go back and edit the trail again (not uploading a new file) and all of the data entered at step 3 is lost

I would understand the user experience if uploading a new GPX would overwrite what was entered at step 3, but the fact that it happens on every edit would be confusing to new users, I think. Just sharing my experience.

**Comment by Flomp** [comment]
I was just able to replicate this. That is definitely not intended. Will investigate!

**Comment by Flomp** [comment]
I just published v0.2.1. This should fix the problem.

**Comment by mmanjos** [comment]
Many thanks! :tada: I can confirm that v0.2.1 fixes this issue
