### ISSUE TITLE
Export All Trails

### ISSUE THREAD

**Issue by elmodor** [Flomp/wanderer#33]
Hi,

it would be nice to have the ability to export all trails at once.
This could be enhanced by various option:
* In Profile: Export All
* Trails/Map View: Export current visible

The export feature could be customizable to export the selected/all of existing data:
* GPX
* Photos
* Summit Book

**Comment by Flomp** [comment]
This feature is now available in v0.8.0 via the Settings page.

**Comment by elmodor** [comment]
Thank you :heart:
