### ISSUE TITLE
French traduction

### ISSUE THREAD

**Issue by seb2020** [Flomp/wanderer#34]
Hi,
I didn't see french for the webapp. If you want, I can make a traduction on https://translate.codeberg.org/projects/wanderer/wanderer/

Tell me if you want ;)

**Comment by Flomp** [comment]
Absolutely! Thanks!

**Comment by seb2020** [comment]
I have translated almost everything

**Comment by Flomp** [comment]
Thank you very much! I'll include it in the next patch.
