### ISSUE TITLE
[Documentation] How do I update the app?

### ISSUE THREAD

**Issue by ludrol** [Flomp/wanderer#35]
I want to QA my translation but when I try to run the app in docker it has older version that I installed yesterday. 

`sudo docker rm wanderer-search wanderer-db wanderer-web`
`sudo docker compose up -d`

**Comment by ludrol** [comment]
```
sudo docker pull wanderer-web
Using default tag: latest
Error response from daemon: pull access denied for wanderer-web, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by ludrol** [comment]
`sudo docker compose pull`

worked

still documentation should be updated

**Comment by Flomp** [comment]
Updated the [docs](https://github.com/Flomp/wanderer/wiki/Installation#updating).
