### ISSUE TITLE
Validation errors are swallowed by "Error creating user"

### ISSUE THREAD

**Issue by jwjenkin** [Flomp/wanderer#38]
Tried creating a user on my phone and kept getting "issue creating user". Hopped on my desktop and had to dig into the response to see the issue was that my username was too short.

Should have those validation errors propogate up. I can give it a go later if I have a chance to dig into the code.

**Comment by Flomp** [comment]
I wasn't aware of that restraint on the username length. It comes from PocketBase. I added a client side validation for the next patch.

**Comment by jwjenkin** [comment]
It's mainly due to me just using 2 characters, but thanks!

**Comment by Flomp** [comment]
Validation added in v0.3.0.
