### ISSUE TITLE
Disable regular registration and login and only allow Oauth2

### ISSUE THREAD

**Issue by poVoq** [Flomp/wanderer#41]
When linking accounts to an main service via the new OIDC login option: https://github.com/Flomp/wanderer/issues/24 it would be great if you could just completely disable the regular account features and only allow OIDC.

Thanks!

**Comment by Flomp** [comment]
![wanderer_disable_login](https://github.com/Flomp/wanderer/assets/26000991/d93e4bd9-97c5-4a04-961f-1b23aab55a2e)
With the next patch, you can disable username, email or both logins via PocketBase.

**Comment by Flomp** [comment]
This is now available in v0.3.1.
