### ISSUE TITLE
[Feature] As a cyclist I want to filter on distances >20km as all my tracks are >20km

### ISSUE THREAD

**Issue by bergziege** [Flomp/wanderer#44]
Hi,
as almost all my tracks/trails are longer than 20km, the current distance filter is almost useless and I would like to have the max filter value as at least one of the following:

- static value at 200km
- as a setting in docker-compose
- as a setting in the app
- dynamically by the longest track out of all my tracks

I found [this code](https://github.com/Flomp/wanderer/blob/main/web/src/routes/trails/%2Bpage.ts) but have no idea if its really just as simple as to change those values (sry, not a js guy)?

**Comment by Flomp** [comment]
I decided to go with option 4 and make it a dynamic parameter. The change will be included in the next patch.

**Comment by bergziege** [comment]
Ohhh thats beautiful. Works like a charm. Thank you!
