### ISSUE TITLE
Auto importet maps via upload folder not visible in map view

### ISSUE THREAD

**Issue by PaddyPat** [Flomp/wanderer#46]
Hi,
i tryed your auto import.

- auto importet gpx files are visible in list view (time attribute from gpx file is ignored - want to import 1400 gpx files from last 10 yrs)
- gpx files are not visible in map view
   those gpx files are from garmin connect - export all via https://github.com/pe-st/garmin-connect-export
  If i delete auto uploadet track and upload it via webui, its visible in map view (doesn't enable "public visible",.. only default)
  Issue is - auto imported gpx files need a category to display in map view
  An fast option for "search after hike - select all hikes and change category to hike" would be nice!
br

**Comment by Flomp** [comment]
Thanks for the report. I was able to fix the bug, that imported trails are not showing up in map view. This will be fixed with the next patch.

However, I cannot replicate your issue that the GPX time attribute is being ignored. Could you please provide an example file?

**Comment by PaddyPat** [comment]
If I today upload a hike from Sunday, it is ordered by *creation date* as latest hike and if I upload tomorrow a hike that is 1yr old, it is the latest hike.

I mean there should be an option to select the date, when the hike was done and also during autoupload an option to read from a gpx file time attribute, where creation date from the hike is visible.

than you could display a month view like a calendar with your hikes ;-)

**Comment by PaddyPat** [comment]
via link you will find 3 gpx files from garmin / komoot with older dates 
https://privatebin.io/?7ce4dcd2f8b24f09#EGsKojwhEvgSX7FAieXaxyLS6rvgkzPrGdxdA89muB3X 
The dates should be visible in the importet tracks to see - this hike / bike route was 2017, this one 2029,.. and also sort it by date

**Comment by Flomp** [comment]
I understand. I will add a date field to the trails and add a filter for it. I like the idea of the calendar!

**Comment by Flomp** [comment]
Calendar added in v0.10.0.
