### ISSUE TITLE
Internal server error 500 when accessing trials or map without signing in.

### ISSUE THREAD

**Issue by raoulmelaet** [Flomp/wanderer#47]
First off all, thank you very much for creating and sharing this awesome project!

I do seem to have an issue where the trials and map sections throw an 500 internal error whenever I am not signed in. I do have some trials that should be publicly available. Everything works however when signed into an account.

From the Home page I am able to access the public trails, so they are definitely available.

![Screenshot from 2024-04-05 15-30-08](https://github.com/Flomp/wanderer/assets/6129414/759378e2-610c-4608-90d9-63358c166ac0)
![Screenshot from 2024-04-05 15-29-36](https://github.com/Flomp/wanderer/assets/6129414/b6bdd576-78f4-4e75-8e1f-fe29d094adfe)

**Comment by Flomp** [comment]
Glad you like wanderer! You're totally right. This will be fixed by tonight.

**Comment by Flomp** [comment]
Fixed as of v0.3.2. Sorry for the inconvenience.
