### ISSUE TITLE
Feature request: add waypoint via click on map

### ISSUE THREAD

**Issue by garbast** [Flomp/wanderer#5]
It would be nice, to be able to add new waypoints via clicking on the map and not need to enter lat/lngs as overlay

**Comment by Flomp** [comment]
With the new release v0.2.0 you can now drag and drop waypoint markers when creating/editing a trail.

**Comment by garbast** [comment]
Cant see how to use this. When i click the button it opens the layer and if i pull the button it does nothing.

![Bildschirmfoto vom 2024-03-25 09-39-03](https://github.com/Flomp/wanderer/assets/5036924/0ccd186d-8e12-4455-8003-25e5bfe78a2c)

**Comment by garbast** [comment]
Yeah okay, you add the coodinate at 0, 0 and then drag it to the area your track is. If you want to add multiple waypoints, this could get out of hand quickly.

My idea would be to right click on the map and the dialog opens with the right clicked coordinate.

You decide if the issue is fullfilled or not. Close the ticket if it's not worth the extra efford.

**Comment by Flomp** [comment]
The marker will always appear in the center of your current map segment. So if you are already focused on your trail, it should be quite convenient to move the marker to the precise desired position.

**Comment by garbast** [comment]
Sorry my bad. You are right. This way is sufficient enough. Thanks for taking care and clearify my missunderstanding.
