### ISSUE TITLE
[HOW TO] Setup wanderer after NPM/Proxy

### ISSUE THREAD

**Issue by berils** [Flomp/wanderer#53]
Hi developers,

Can you please write instruction, guide how to setup wanderer after nginx proxy manager(npm)?
Localy its running pretty cool, but im facing issues when i want to share it my friends/WWW.

**Comment by Flomp** [comment]
Could you please specify what issues you are facing?
I'm running wanderer behind npm on my raspberry pi without any problems.

**Comment by berils** [comment]
Using, freshly installed docker+compose ,
Ubuntu 22.04
changed origin IP to local IP (http://x.x.x.35:3000)
NPM config for host:
![image](https://github.com/Flomp/wanderer/assets/12886866/85631f76-b3e2-44fb-9eaf-ee23a585c5f5)
Locally i can login successfully, but when accessing from WWW, getting 403
![image](https://github.com/Flomp/wanderer/assets/12886866/ea9abe6b-a853-417f-b520-9e577c762ddd)

**Comment by Flomp** [comment]
My point from your [previous issue](https://github.com/Flomp/wanderer/issues/19#issuecomment-2016576241) still stands: I would be interested in the JSON part of the 403 response.

**Comment by berils** [comment]
Hi again,
so i made poor quality gif, but i found in preview section (selecting X login) text: 
"Cross-site POST form submissions are forbidden"
![image](https://github.com/Flomp/wanderer/assets/12886866/b3186960-efe1-4aa3-83d9-3bdcbe3b7bce)
poor gif:
![Animation](https://github.com/Flomp/wanderer/assets/12886866/89eab20a-4f4a-47a4-aa87-14fe6948d32a)

**Comment by berils** [comment]
Yes sir!
Problem solved, thanks to your share!
So if using NPM ORIGIN should **not** include :3000 at the end. Then everything is working as expected.
