### ISSUE TITLE
Still listens on port 3000 even with port changed in docker-compose

### ISSUE THREAD

**Issue by kokesh** [Flomp/wanderer#54]
I've changed the port before installing with Docker compose to 5000, after installing it still listens on 3000.

From docker log:
Listening on 0.0.0.0:3000

**Comment by Flomp** [comment]
You cannot change the internal port that the node application runs on (well, technically you can but you will need to change it in the Dockerfile and build the image yourself). But I don't see a reason why you would need to. If you want to make wanderer available on port 5000 on your host machine it is enough to change the port mapping for the wanderer-web service in the docker-compose file to:
```
web:
...
  ports:
      - "5000:3000"
 ...
```

**Comment by kokesh** [comment]
Yes, that works! I'm dumb and changed both ports in the compose file.
