### ISSUE TITLE
[Feature] Share trails between users

### ISSUE THREAD

**Issue by berils** [Flomp/wanderer#55]
Hi,
Maybe this is not feature, but I can't see option how to share track to other users.
I can see only my uploaded tracks and can't find button/way how to share to other users.

Sincerely,
Berils.

**Comment by Flomp** [comment]
Thanks for the suggestion. This feature is already on the [roadmap](https://github.com/users/Flomp/projects/2/views/1) and will likely be added in v0.6.0.

**Comment by Flomp** [comment]
I just released v0.6.0. You are now able to share trails with other users.
