### ISSUE TITLE
Track not show in map view, NaNs in some fields

### ISSUE THREAD

**Issue by WetenSchaap** [Flomp/wanderer#56]
Some of my GPX files are not showing up in the map view. They do appear in the list on the left. For instance:

![image](https://github.com/Flomp/wanderer/assets/36634689/ee8d21e5-d4a6-4675-aad4-5e22f6009b0e)

"Haute Route 4..." is not visible. Clicking on it will open the specific track, and *is* drawn on the map:

![Screenshot from 2024-05-03 10-40-56](https://github.com/Flomp/wanderer/assets/36634689/4d79e836-3f34-43e3-ac55-ea0801993a38)

*y* and *m* are show as NaN.

This happens with some GPX files I downloaded, [this is an example just for reference](https://notebin.de/?9774a4ec9599478a#3EAXpnYXGL9C3568kgaEtNxK4XPpLfg2tznLdZAqQfua). The raw GPX file does not look like it has broken syntax.

**Comment by Flomp** [comment]
Thanks for the report. The supplied track does not use the `<trk>` tag to store the track, but instead uses the `<rte>` tag. wanderer currently disregards this tag. I will include a fix in the next patch.

**Comment by Flomp** [comment]
The bug should be fixed now in v0.5.1.

**Comment by PaddyPat** [comment]
Gpx import and Date import from old tracks (delete data.ms) as changelog hint doesn’t also no work. (Import from upload path).
Date is only shown if I edit a old track and save it.

**Comment by WetenSchaap** [comment]
Confirming it works on my end now. Thanks!
