### ISSUE TITLE
Add Track Name Metadata to exported GPX file

### ISSUE THREAD

**Issue by githubhacs** [Flomp/wanderer#57]
**_For Trails created within the application._**

A Trail's exported GPX (.xml ) file does not have a Name set in the metadata.

A track name can be set by inserting a metadata name tag for the track:

`<trk><name>TRACK NAME  HERE</name><trkseg>`

example:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><gpx version="1.1" creator="wanderer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"><trk><name>TRACK NAME</name><trkseg><trkpt lat="00.000000" lon="-0.00000"><ele>000</ele></trkpt>
```

Can the downloaded/exported track please include the Trail Name as the Track name?

**Comment by Flomp** [comment]
v0.5.1 adds more extensive trail exporting support. Exported gpx/geojson files now include the trail name.

**Comment by githubhacs** [comment]
Thanks for the updates.

The inclusion of Vallaha is a massive boost.

Great product.
