### ISSUE TITLE
Add ability for own branding (logo, site name)

### ISSUE THREAD

**Issue by anarion80** [Flomp/wanderer#59]
Hello!

It would be great if there was possibility for own branding:

- Change the logo
- Change the "Welcome to <whatever>" text
- Change the hero text
- Disable user registration/login

to be used for example for local non-profit tourist organization to showcase their trails.

**Comment by Flomp** [comment]
Hey there,

Disabling user registration/login is possible by setting the `PUBLIC_DISABLE_SIGNUP` environment variable to false (see `docker-compose.yml`). 

I currently do not plan to add branding options. You can of course build the wanderer-web image yourself. All logos are stored in `/web/src/lib/components/logo`as svelte files and you can simply replace the SVG with your own. To find all "wanderer" strings just do a search and replace them however you like.

When you are done simply run this from the project root:
```bash
cd web && npm ci --omit=dev && npm run build && cd ..
docker build web/ --no-cache  -t <your-custom-wanderer-image-tag>:latest 
```
And don't forget to change the docker-compose.yml to use your custom image.

**Comment by anarion80** [comment]
Thanks, I got it to work: https://trasy.pttkstaszow.info/
You can comment if the attribution is ok/enough and then close.

**Comment by Flomp** [comment]
That's perfectly fine. Thanks. Happy I could help.
