### ISSUE TITLE
No Signup link after installing

### ISSUE THREAD

**Issue by kokesh** [Flomp/wanderer#61]
I've removed and reinstalled Wanderer (deleted all containers/images/volumes) and did 
`docker compose pull && docker compose up -d`

Now it is up, but I don't see any registration link. 
How do I create new user? Is this a bug?

**Comment by Zing0s** [comment]
I cant make a new user. Gives me an error. Any clue?
Vanilla docker compose file other than external port number change in the database.

**Comment by thekennyriley** [comment]
@Zing0s From the note in the docs on https://wanderer.to/getting-started/installation/#from-source
I had to change the ORGIN variable to my docker host IP and it worked for me

**Comment by Zing0s** [comment]
> @Zing0s From the note in the docs on https://wanderer.to/getting-started/installation/#from-source I had to change the ORGIN variable to my docker host IP and it worked for me

Thanks a lot! It worked. 
Now I having trouble of getting my first trail saved. WTF. 
Thanks anyway.
