### ISSUE TITLE
Update account password

### ISSUE THREAD

**Issue by sgued** [Flomp/wanderer#63]
Hi,

Thank you for this tool, it's really nice to be able to nicely share trails with other people.

Playing around with it I have a couple of questions/feature suggestions.

Is is not possible to update one's password?

**Comment by Flomp** [comment]
Hi,
glad you like it. It is currently possible however only through pocketbase admin UI. I agree that this feature should be available through the website itself. I will put it on the roadmap.

**Comment by Flomp** [comment]
This feature was added in v0.8.0.

**Comment by BastLast** [comment]
this should be closed no ? given that it is implemented ?
