### ISSUE TITLE
Logging in from Another Computer

### ISSUE THREAD

**Issue by iSAT32196** [Flomp/wanderer#67]
Hello! I have a bit of a weird issue. I've installed Wanderer through docker on a computer I have running Ubuntu I use as a "server" pc. When I access Wanderer on the server pc by going to localhost:3000, everything works fine. However, when I'm on my main computer (Windows 11) or on my macbook (Sonoma 14.5) and I go to log into Wanderer by using the Server Pcs IP address, I get a popup that says "Error during login". I've double checked I'm using the same login info, and get the same error. I've also tried creating a different account, and get "Error Creating User". 

I'm not sure if you have any suggestions on what to do?

**Comment by iSAT32196** [comment]
Update: I just tried going to serveripaddress:3000 on my server pc, and got the same error. So seems to be something with connecting via IP, but I'm not sure what.

**Comment by Flomp** [comment]
Very likely you forgot to change the ORIGIN env var. In the default config it is set to `http:localhost:3000`. However, if you access the instance via `http://ipaddress:3000` you need to change the env var accordingly in your docker compose file.

**Comment by iSAT32196** [comment]
Okay I'll give that a try, thanks!
