### ISSUE TITLE
Version 0.60 - gpx Import ok, all tracks with wrong names

### ISSUE THREAD

**Issue by PaddyPat** [Flomp/wanderer#68]
Hi,

thanks for your work.

In previous version (0.40 I think) you used the <name> from inside the gpx file and now in 0.60 all files via gpx upload (import folder via docker) are named like trail_importdate

looks like:
trail-2024-06-08T12:10:28.366Z
trail-2024-06-08T12:10:32.533Z

So all trails uploaded via gpx have the same *cryptic* name and not the name from the inside the <name> from gpx file (garmin export has names inside gpx and it’s easier if you have over 1500 gpx files to find it by the right name)

maybe you could use again the original name from inside gpx file?

Br :-)

**Comment by Flomp** [comment]
Hey,
this is very likely related to a change I published in v0.6.0 to resolve #62. This should only affect GPX files that do not carry the name in the `<metadata>` tag. Before v0.6.0 these trails would cause an error when uploaded. Do you maybe have a sample file that I could test with? You can probably delete the actual route data in the file if you don't want to publish it.

**Comment by PaddyPat** [comment]
Sure, I will later upload a few files from Garmin Connect and Komoot.

**Comment by PaddyPat** [comment]
GPX File from Garmin
https://privatebin.net/?a3862d7426a69293#gnJhAa1A3Nw3yTbyd5nqpJiLbGVkrDuCpTu5gfwg8JJ

**Comment by Flomp** [comment]
This should now be fixed in v0.6.1.
