### ISSUE TITLE
Feature request: allow drag and drop upload of images

### ISSUE THREAD

**Issue by garbast** [Flomp/wanderer#7]
When i edit a track i would love to be able to upload multipled images at once via drag and drop upload.

**Comment by Flomp** [comment]
With the new release v0.2.0 you can now drag and drop photos into the photo section when creating/editing a trail.

**Comment by garbast** [comment]
Does not work. When i drag an image in the browser a dashed border appears. On drop i receive an exceptions in the dev tools console:

```DOMException: A requested file or directory could not be found at the time an operation was processed.```

**Comment by Flomp** [comment]
I cannot replicate this issue. I tested all current browsers on both arm64 and amd64. Can you provide more detail (kind of file, os, browser etc.)?

**Comment by garbast** [comment]
I cleared the browser cache and the error persists. As fare as i see the image do not get transfered. In the network tab no traffic gets triggered due to the drop of the image.

Chrome Version 123.0.6312.58 (Offizieller Build) (64-Bit)
Ubuntu 22.04.4 LTS
Image is a jpeg 2.9MB and attached
![20240309_141612](https://github.com/Flomp/wanderer/assets/5036924/848147b6-98be-4ebd-acbe-13734d7aeee4)

**Comment by Flomp** [comment]
The image won't get uploaded before you save the trail. So it's definitely a client-side issue. I cannot replicate the issue with the attached photo either. Does it happen for all photos or just specific ones?

**Comment by garbast** [comment]
I think, the problem is again the large file size as mentioned in the other ticket where you explained the problem with the backend size limit.

**Comment by Flomp** [comment]
I don't think so, because, as mentioned, there is no server-side communication whatsoever when you drag a photo over.

**Comment by garbast** [comment]
You are right the error is locally. After some debugging, i can say, that it still happens with drag and drop but not with selecting via upload field and uploading that way.

All findings on google suggest that the error has something to do with the desktop i use. Im running Ubuntu 22.04 with gnome 42.9

I found an other tool, that drag and drop uploads, with the same error. https://github.com/transloadit/uppy/issues/3505 Maybe the change is something related to wanderer? https://github.com/transloadit/uppy/commit/65f255164594639797022f71e9779d1d7519214c
