### ISSUE TITLE
[Feature request] Expand a trail successively with additional gps tracks

### ISSUE THREAD

**Issue by escuco** [Flomp/wanderer#76]
Hello!

There are trips that may take several days and for which several gpx tracks (e.g. per day) are generated. It would be nice, if I could expand a trail step by step (or day by day) with different following gpx tracks (according to my trip) to one big single one.

If I now share the trail with other users, they can see the current status of my journey at any time when they open my trail.

Jan

**Comment by Flomp** [comment]
Hey!

You can currently replace the GPX file associated with a trail. So you could update your progress that way? Or are you suggesting to allow a trail to have multiple GPX tracks associated with it?

**Comment by escuco** [comment]
Hi!

Yes, the latter. One trail, where the day trips are added bit by bit (per different gpx files) and finally result in one big track (trail, journey).

Example: We're doing a lot of bikepacking tours lasting several days. Each day, I export the individual daily gpx track from my tracking app and it would be very nice to create one trail in _wanderer_ at the beginning of the journey and expand the track in the trail map with the daily gpx track.
So every time interested people look at my trail while I am travelling, they see the current status of my multi-day trip with all the previous photos, waypoints and one single track on the map. (depending on how often I upload gpx tracks, usually once a day)

**Comment by jo-chemla** [comment]
I'm the same kind of user, doing multi-day trips (hiking or bikepacking), and indeed it would be nice to have a concept of "journeys/trips" in addition to trails - which are the current single-file tracks. 

On top of 
 - the ability mentionned by OP to follow how a user progresses along a trip when uploading new segments - or live-broadcasting if anyone has an interest in that
 - the ability for a user to explore a week or two-weeks long trip, with segments, photos and waypoints, as well as e.g. cumulative stats (distance/elevation gain/speed along the track, for the current segment/day or from the start of the trip) is helpful to better understand one's capabilities and plan future trips. 
 - this could longer-term also be useful for the tracks editor, helping a user cut a multi-day itinerary track into multiple segments, also showing each segments stats, for example in a table, to assess whether the chosen cutting is good or not


I've tried a lot of different web or android apps, Komoot has a nice way to display these multi-step trips on the web, see [this example](https://www.komoot.com/fr-fr/discover/Nanterre/@48.8909000,2.2093000/tours?sport=bikepacking&map=true&max_distance=30000&pageNumber=1). When selecting one segment of the trip, this ends-up showing the single-trail portion, with a header that lets the user go back to the multi-segment view, or switch to the previous/next segment. 

![image](https://github.com/user-attachments/assets/076dc2c1-910a-47d4-af3b-58d9bd1a7660)

**Comment by Flomp** [comment]
From a database design perspective I like @jo-chemla idea to rework lists into this feature. I think it should be easy enough to display all tracks contained in a list on a map and calculate the total length/height difference. I'll take a look at it.

**Comment by Flomp** [comment]
This is now available in v0.9.0.
![wanderer_lists](https://github.com/user-attachments/assets/46729d38-e864-480d-9e2b-6072cb2ac8dc)

**Comment by jo-chemla** [comment]
Wow congrats on the implementation, that was fast and that "List of Trails" component is really nicely designed! Will try it out as soon as I get the chance.

**Comment by escuco** [comment]
This is very great and seems to work fine, thank you so much for it!

It would be nice, If one could share a list to public users - as described in #105 

Should we close this issue now?
