### ISSUE TITLE
Use track colour to reflect speed or slope in addition to altitude

### ISSUE THREAD

**Issue by bevalentin** [Flomp/wanderer#80]
Hi,

Currently, the track on the Trail details page is coloured according to the altitude (gradient from green to yellow to red).
It would be nice to be able to select which track property must be represented (using the same or different gradient colours): Altitude, Slope or Speed.
The same properties that are already visible on the "elevation control" component.

BTW, the map on the Trail details page is not visible on my mobile phone (the elevation control is visible, however).
Could it be that its height is reduced to 0px due to the screen size? 

Thank you,

Bernard

**Comment by Flomp** [comment]
Hey,

thanks for the suggestion. This is now available from v0.7.0.

Regarding the 0px that was indeed a problem previously. However, I thought I fixed it two or three versions ago. Could please confirm that it is gone in v0.7.0?

**Comment by oliver124810** [comment]
Sorry to revive this old thread, but I have a question before I unnecessarily open an issue. I would like to visualize the speed or the elevation on the map. I am confused what is supported in 0.16.5. According to this thread and this [screenshot](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fi-made-wanderer-a-self-hosted-trail-and-gps-track-database-v0-bu1capuv7roc1.png%3Fwidth%3D3232%26format%3Dpng%26auto%3Dwebp%26s%3Df37ce902bf05b3861322e30521acee3cc77a9c7e
), the track on the map should be colored, but in my case, it is just blue. It is also plain blue on the demo server. Also, the elevation profile is slightly colored, but only its border, which makes it hard to see. It does not look like the screenshot above.
Am I missing something?
