### ISSUE TITLE
Topographic maps

### ISSUE THREAD

**Issue by domodwyer** [Flomp/wanderer#81]
First off - I love wanderer! Thank you for making and sharing this ❤️ 

The map view is excellent already, but I often find topographic maps helpful when planning an activity in mountainous areas, and OpenStreetMaps has a topographic project ([wiki](https://wiki.openstreetmap.org/wiki/OpenTopoMap)) and tiles: https://opentopomap.org/

Would this be easy to integrate?

**Comment by Flomp** [comment]
Good idea! Implemented in v0.7.0. Thanks!
