### ISSUE TITLE
Public access via Cloudflare tunnels

### ISSUE THREAD

**Issue by thekennyriley** [Flomp/wanderer#82]
I'm encountering a 500 Internal Server Error when accessing the 'trails' section from outside my project using the Cloudflare tunnel. While I can successfully view the home page, subsequent attempts to navigate to 'trails' result in an error.

I suspect the issue might be related to the ORIGIN variable, as I'm unsure of its proper configuration for allowing cross-origin requests. However, despite my attempts to adjust this setting within the project and in Cloudflare's dashboard, the problem persists.

**Comment by Flomp** [comment]
You are right that this is likely due to an incorrect ORIGIN variable. It needs to be set to whatever you type in your browser to reach wanderer. So something along the lines of `http(s)://<my_domain_or_ip>:<my_port>`.

**Comment by thekennyriley** [comment]
I can't use a port from the outside. It's set up for `https://mydomain.domain.com`, and in the tunnel, the service is set to `HTTP://wanderer.domain.com`. I am able to access it internally so its something between Cloudflare and wanderer

**Comment by thekennyriley** [comment]
It's got something to do with https. if I navigate to http://mydomain.domain.com/maps from the outside it works but it will automatically switch back to https and stop working.

**Comment by Flomp** [comment]
I see. I'm unfortunately not familiar with cloudfare tunnels.

And setting the ORIGIN to `https://mydomain.com` doesn't work, I assume? E.g. the demo uses a reverse proxy. So on the server itself it is available at `http://localhost:3000`, however the ORIGIN is set to `https://demo.wanderer.to`.

**Comment by thekennyriley** [comment]
I was able to fix the issue by changing the ORIGIN to https://mydomain.domain.com and removing port 3000. Now everything works perfectly.

**Comment by Flomp** [comment]
Great, happy it worked.
