### ISSUE TITLE
Allow custom map tile sets

### ISSUE THREAD

**Issue by tgrosinger** [Flomp/wanderer#84]
I would love to be able to change the tileset used on the maps. For example, ThunderForest has several different maps aimed at specific use cases:

- https://tile.thunderforest.com/outdoors/{z}/{x}/{y}.png?apikey=...
- https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=...
- https://tile.thunderforest.com/neighbourhood/{z}/{x}/{y}.png?apikey=...
- etc.

Ideally it would be possible to configure these globally, and then set a preferred map based on the trail category. It could also be overridden when viewing a trail.

Thank you! Wanderer is amazing.

**Comment by Flomp** [comment]
Thank you for the suggestion. With v0.7.0 I introduced OpenTopoMaps tiles. It would indeed be fairly simple to let the user add custom tilesets. I'm planning to overhaul the settings menu. I think I will include it there.

**Comment by Flomp** [comment]
Adding custom tilesets is now possible in v0.8.0.

**Comment by tarmacalastair** [comment]
Would it be possible to provide some guidance on how to create a json file for this please? I use the below xml file for Oruxmaps and Mobile Atlas Creator on my phone for UK Ordnance Survey maps but I have no idea how to create a json file. I also have a Thunderforest API key but again no idea how to create the json files. 

This is my XML file for Ordnance Survey maps:

```
<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
<name>OS Maps with Key</name>
<minZoom>0</minZoom>
<maxZoom>18</maxZoom>
<tileType>png</tileType>
<tileUpdate>None</tileUpdate>
<url>[http://ak.t3.tiles.virtualearth.net/tiles/r{$q}.png?g=3440&productSet=mmOS&key=PUT-YOUR-API-KEY-HERE](http://ak.t3.tiles.virtualearth.net/tiles/r%7B$q%7D.png?g=3440&productSet=mmOS&key=PUT-YOUR-API-KEY-HERE)</url>
<backgroundColor>#000000</backgroundColor>
</customMapSource>
```
