### ISSUE TITLE
[bug] Missing icons for trail settings

### ISSUE THREAD

**Issue by entnx-01** [Flomp/wanderer#85]
When I open a track and navigate to Settings (three dots) there a multiple icons missing. Some others like "Show on map" are displayed correctly. 

<img width="122" alt="image" src="https://github.com/Flomp/wanderer/assets/6429325/32f1d0d4-fc02-4b4a-9c80-43f0c2876a87">

Thanks for you work I really like your tool!

**Comment by Flomp** [comment]
Thanks for the hint. I fixed it for the next patch.
