### ISSUE TITLE
API: Trail ID

### ISSUE THREAD

**Issue by githubhacs** [Flomp/wanderer#86]
hi,

**problems**
cannot search for Trails by easily known data to retreive Trail ID.
when a Trail is created by the Upload endpoint the ID is not available in the response.

The API's Trail endpoint performs a search using the ID ( https://wanderer.to/api-reference/trail/ ).
The only way I see to obtain the ID is by opening the view for the Trail.

Why do I care? :-)

I have a utility which will parse a GPX file, or if the file contains multiple days it'll split into separate tracks / files then:
* using the Track's starting point's lat/lon lookup the address.
  * perform all manner of address munging depending on the address length.
* using the GPX creator value sets an activity type.
* get the Track's start Date and Time.

The new GPX track name is set as:
* YYYY-MM-DD-gpx_activity_type-TrackStartLocation-TrackStartCountry+TrackStartPostcode

The new GPX Filename is set as:
* YYY-MM-DD-GPX_ACTIVITY_TYPE-**NOT_UPLOADED**-COUNTRY.gpx

This file will be uploaded to Wanderer, hence NOT_UPLOADED in the filename.
Once it's been uploaded the NOT_UPLOADED portion of the filename becomes UPLOADED.

The aim is: once the the GPX file has been uploaded I can set various the Trail's properties using the Trail's Track Name data via the API.

To enable this the Trail ID is needed :-)

Thanks.

**Comment by Flomp** [comment]
Thanks for the hint. This is now fixed in v0.7.2.

**Comment by githubhacs** [comment]
Thanks very much, the ID is now returned.
