### ISSUE TITLE
API: POST /trail/{id} - extend supported properties

### ISSUE THREAD

**Issue by githubhacs** [Flomp/wanderer#87]
This endpoint only supports changing the **name** property.

Can this please be extended to support:

```
category
collectionId
collectionName
description
difficulty
location
```

Thanks.

**Comment by Flomp** [comment]
The docs were wrong in this case (I updated them just now). `category`, `description` and `difficulty` can all be changed via the update endpoint. `collectionId` and `collectionName` cannot be changed as these describe the table that the trails are stored in. Changing them would break the application. Note that `category` must be a valid category id.

**Comment by githubhacs** [comment]
Thanks for the clarification. The `location` property is available to update too.

**Comment by Flomp** [comment]
In case your last sentence was meant as a question, then yes the `location` field can also be updated via this endpoint.

**Comment by githubhacs** [comment]
All good, thanks again.
