### ISSUE TITLE
Feature request: Show lists as map

### ISSUE THREAD

**Issue by garbast** [Flomp/wanderer#9]
Currently its possible to show lists as card or list. I would be nice to show them as map.

So it's like using the map module with a preselected list as filter.

**Comment by Flomp** [comment]
With the new release v0.2.0 you can now toggle between map and list mode when you are on the trail list page (`/lists`).

**Comment by garbast** [comment]
Works seamlessly.

Only suggestion would be to add/move the function to the "Display as" selectbox to have them all in one place.
