### ISSUE TITLE
Feature request: Allow guests to download gpx files for trails they have access to

### ISSUE THREAD

**Issue by BastLast** [Flomp/wanderer#92]
I cannot find a way as a non owner to download the gpx file of a trail :/

**Comment by Flomp** [comment]
This is fixed in v0.8.1.

**Comment by jo-chemla** [comment]
You might want to add [automations](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-built-in-automations) to your wanderer github project 
 - so whenever an item is moved to Done, then the corresponding issue gets closed
 - Another automation could also auto-add every issue opened on the repo to a catefory like `needs-triage`
