### ISSUE TITLE
[BUG] garmin connect refuse to import a gpx file exported from wanderer

### ISSUE THREAD

**Issue by BastLast** [Flomp/wanderer#93]
this to me is a quite important thing , why would the gpx file be destroyed ?

**Comment by Flomp** [comment]
I tried to debug the issue a bit:
wanderer produces valid GPX. It seems that garmin is a bit particular about the format that the file needs to have.

1. Exported gpx files were missing a XML header attribute that I now added
2. All trackpoints must have a time associated with them. If that is not present the file will be rejected.

**Comment by BastLast** [comment]
will it be possible to fix that and migrate the data to be compatible again ?

**Comment by Flomp** [comment]
The missing header is now added in v0.8.1. I checked it with some files and it seemed to work. Please let me know if you run into issues.

**Comment by BastLast** [comment]
Ill update later todat and update u

**Comment by BastLast** [comment]
tested and confirm it works fine now :) thanks a lot !
