### ISSUE TITLE
Detailed view availability for unregistred users ?

### ISSUE THREAD

**Issue by jarex691** [Flomp/wanderer#94]
Thank you for your fantastic job  ! Is it possible to provide a wide view of the trace also to unregistered users ? If not then maybe it would be worthwhile to display info somewhere in the default layout , what are the benefits of registration. I think that the average user doesn't even realize how much more useful is the view with height profile and additional information. Besides, an attempt to display a wider view ending up with a blank map is perceived as an application error rather than a barrage of user logins. It would be good to make users aware that access to the detailed view depends on registration. Or (better) let the administrator choose whether he wants to make the detailed view also available to non-logged-in users.

**Comment by Flomp** [comment]
Hi,

that is indeed not intended and was introduced with the last patch. It will be fixed with the next one.

**Comment by BastLast** [comment]
is this the reason why i have this huge white thing as an unregistered user ? 
![image](https://github.com/user-attachments/assets/7c82db29-ee01-4426-9b48-b494ec69b1fb)

**Comment by BastLast** [comment]
gray indeed aha, personally i would love for unregistered user to have access to gpx files and info on public trails , can we make those permission configurable ?

**Comment by Flomp** [comment]
This is fixed in v0.8.1.
