### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Fmstrat** [Flomp/wanderer#95]
When starting using the `docker-compose.yml` file, this error is returned:

```
|wanderer-web  | 2024-07-23T11:09:52.404675075Z SyntaxError: Unexpected token < in JSON at position 0
|wanderer-web  | 2024-07-23T11:09:52.404740313Z     at JSON.parse (<anonymous>)
|wanderer-web  | 2024-07-23T11:09:52.404751472Z     at parseJSONFromBytes (node:internal/deps/undici/undici:5584:19)
|wanderer-web  | 2024-07-23T11:09:52.404758636Z     at successSteps (node:internal/deps/undici/undici:5555:27)
|wanderer-web  | 2024-07-23T11:09:52.404765042Z     at fullyReadBody (node:internal/deps/undici/undici:1665:9)
|wanderer-web  | 2024-07-23T11:09:52.404770979Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|wanderer-web  | 2024-07-23T11:09:52.404777002Z     at async specConsumeBody (node:internal/deps/undici/undici:5564:7)
|wanderer-web  | 2024-07-23T11:09:52.404782858Z     at async Object.handle (file:///app/build/server/chunks/hooks.server-49W1TjIe.js:44:23)
|wanderer-web  | 2024-07-23T11:09:52.404788679Z     at async respond (file:///app/build/server/index.js:3899:22)
|wanderer-web  | 2024-07-23T11:09:52.404794632Z     at async Array.ssr (file:///app/build/handler.js:1243:3)
```

No other info is provided. Other than changing the Meili master key, the only other changes I've made are to the container names (these are running with other things, so `db` is just too generic since I don't use project names), and of course the bind mount paths.

**Comment by Flomp** [comment]
Since you renamed the service: did you make sure to also adapt the connection to the backend?
https://github.com/Flomp/wanderer/blob/0d6d034ed524bd339da498a2a24042e5ded4bcae/docker-compose.yml#L54

`http://db:8090` needs to be `http://<your_service_name>:8090`

**Comment by Flomp** [comment]
The `PUBLIC_` is a [svelte convention](https://kit.svelte.dev/docs/modules#$env-dynamic-public) and simply means that the env variable is available on the client side and on the server side. The db container does not need to be public. It is accessed only from the server side.

**Comment by Fmstrat** [comment]
Thanks, ended up just using it for the admin console/OAuth, though. so handy there. Thanks again!
