### ISSUE TITLE
[Bug] Default category is re-applied when editing an existing trail record

### ISSUE THREAD

**Issue by bevalentin** [Flomp/wanderer#96]
Hi,

When an existing trail is edited, the default category selected in the settings is re-applied automatically.
The category from the trail record should be used instead.

Thank you!

**Comment by BastLast** [comment]
ahhh so that's why my trails have been changing category all the time lol i was wondering if i was just crazy

**Comment by Flomp** [comment]
Thanks, will be fixed in the next patch.

**Comment by Flomp** [comment]
Fixed in v0.8.1.
