### ISSUE TITLE
[Feature] Automatically add Summit Book entry when creating a trail

### ISSUE THREAD

**Issue by bevalentin** [Flomp/wanderer#97]
Hi,

For some time I wondered how the "Completed / Not completed" flag was set then I figured out it required me to create an entry in the Summit Book.

The majority of the trails I create contains GPS tracks I have recorded myself. I presume this is the same for most users.
So currently I must add a Summit Book entry manually for each track I create.

I suggest adding a default Summit Book entry automatically in the New Trail form (when the GPX file is uploaded).
This would use the logging date of the tracked data.
This feature could be turned on/off using a new option in the settings.

Thank you!

**Comment by Fmstrat** [comment]
This could be tied to if a file was uploaded. The GPX is most commonly from a route that's been previously traversed.

**Comment by Flomp** [comment]
As of v0.10.0 this is now the default. A summit log entry will be added automatically when a new GPX file is uploaded.
